export const projects = [
  {
    title: "Get ahead",
    subtitle: "iA Financial Group",
    year: "2025",
    image: "/images/work_projects_1.png",
  },
  {
    title: "Everyone’s Pharmacy",
    subtitle: "Jean Coutu",
    year: "2024",
    image: "/images/work_projects_2.jpg",
  },
  {
    title: "Widescape",
    subtitle: "Widescape",
    year: "2022",
    image: "/images/work_projects_3.jpg",
  },
  {
    title: "OKA",
    subtitle: "OKA",
    year: "2022",
    image: "/images/work_projects_4.jpg",
  },
  {
    title: "Opto-Réseau",
    subtitle: "Opto-Réseau",
    year: "2021",
    image: "/images/work_projects_5.jpg",
  },
  {
    title: "Coup Fumant",
    subtitle: "Coup Fumant",
    year: "2021",
    image: "/images/work_projects_6.jpg",
  },
  {
    title: "Shelton",
    subtitle: "Shelton Brewery",
    year: "2020",
    image: "/images/work_projects_7.jpg",
  },
  {
    title: "Best",
    subtitle: "GardaWorld",
    year: "2021",
    image: "/images/work_projects_8.jpg",
  },
  {
    title: "À table avec l'histoire",
    subtitle: "La Fondation BAnQ",
    year: "2021",
    image: "/images/work_projects_9.jpg",
  },
  {
    title: "La Coop fédérée becomes Sollio Groupe Coopératif",
    subtitle: "Sollio",
    year: "2019",
    image: "/images/work_projects_10.jpg",
  },
  {
    title: "Lamajeure",
    subtitle: "Lamajeure",
    year: "2019",
    image: "/images/projects_img_2.jpg",
  },
  {
    title: "Synesthesia",
    subtitle: "Orchestre Symphonique de Montréal",
    year: "2019",
    image: "/images/work_projects_11.jpg",
  },
  {
    title: "100 Temps",
    subtitle: "La Fondation BAnQ",
    year: "2020",
    image: "/images/work_projects_12.jpg",
  },
  {
    title: "Crisis24",
    subtitle: "GardaWorld",
    year: "2021",
    image: "/images/work_projects_13.jpg",
  },
  {
    title: "We see you like no other",
    subtitle: "Opto-Réseau",
    year: "2020",
    image: "/images/projects_img_1.jpg",
  },
  {
    title: "Open",
    subtitle: "PME MTL",
    year: "2020",
    image: "/images/work_projects_14.jpg",
  },
  {
    title: "Fruité",
    subtitle: "Lassonde",
    year: "2019",
    image: "/images/projects_img_3.jpg",
  },
];
